"""Aggregate fail-closed native-host initialization reproduction evidence."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Mapping, Sequence

from .layercake_domains import (
    DomainConformanceError,
    _canonical_sha,
    _sha256_file,
    _write_json,
)


PROTOCOL_FORMAT = (
    "abi-layercake-native-host-three-initialization-reproduction-protocol/1"
)
EVIDENCE_FORMAT = (
    "abi-layercake-native-host-three-initialization-reproduction-evidence/1"
)
VALIDATION_FORMAT = "abi-layercake-native-host-semantic-validation/1"


def _read_object(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise DomainConformanceError(f"invalid JSON evidence: {path}") from exc
    if not isinstance(value, dict):
        raise DomainConformanceError(f"JSON evidence must be an object: {path}")
    return value


def _relative_file(root: Path, value: str) -> Path:
    path = (root / value).resolve()
    try:
        path.relative_to(root)
    except ValueError as exc:
        raise DomainConformanceError(
            "reproduction evidence path escapes repository"
        ) from exc
    if not path.is_file():
        raise DomainConformanceError(f"reproduction evidence is missing: {value}")
    return path


def _claimed_evidence_hash(value: Mapping[str, Any]) -> str:
    payload = dict(value)
    claimed = payload.pop("evidence_sha256", None)
    if not isinstance(claimed, str) or claimed != _canonical_sha(payload):
        raise DomainConformanceError("validation evidence claim hash mismatch")
    return claimed


def aggregate_host_reproduction(
    *,
    protocol_path: str | Path,
    output_path: str | Path,
) -> dict[str, Any]:
    protocol_path = Path(protocol_path).resolve()
    repository_root = protocol_path.parent
    output_path = Path(output_path).resolve()
    protocol = _read_object(protocol_path)
    if (
        protocol.get("format") != PROTOCOL_FORMAT
        or protocol.get("status")
        != "PREREGISTERED_AFTER_SINGLE_HOST_PROMOTION_GATES_BEFORE_REPRODUCTION_RUNS"
        or protocol.get("reproduction_unit")
        != "fresh_process_and_fresh_onnxruntime_session_initialization"
        or protocol.get("final_test_accessed") is not False
    ):
        raise DomainConformanceError("host reproduction protocol is invalid")
    candidate = protocol.get("candidate")
    gate = protocol.get("per_initialization_gate")
    initializations = protocol.get("initializations")
    if (
        not isinstance(candidate, dict)
        or not isinstance(gate, dict)
        or not isinstance(initializations, list)
        or [row.get("id") for row in initializations]
        != ["host-init-1", "host-init-2", "host-init-3"]
    ):
        raise DomainConformanceError("host reproduction protocol is incomplete")

    rows: list[dict[str, Any]] = []
    observation_hashes: list[str] = []
    for initialization in initializations:
        relative = initialization.get("existing_functional_evidence")
        if relative is None:
            relative = initialization.get("output")
        if not isinstance(relative, str):
            raise DomainConformanceError("initialization evidence path is invalid")
        path = _relative_file(repository_root, relative)
        evidence = _read_object(path)
        claimed_hash = _claimed_evidence_hash(evidence)
        expected_hash = initialization.get("existing_functional_evidence_sha256")
        if expected_hash is not None and expected_hash != claimed_hash:
            raise DomainConformanceError(
                "preregistered initialization evidence hash changed"
            )
        capability_metrics = evidence.get("capability_metrics")
        if not isinstance(capability_metrics, dict):
            raise DomainConformanceError("capability metrics are missing")
        observations = evidence.get("observations")
        if not isinstance(observations, list):
            raise DomainConformanceError("validation observations are missing")
        # Per-request latency is expected to vary across fresh processes.  The
        # semantic payload and generated bytes must not.
        semantic_observations = [
            {key: value for key, value in observation.items() if key != "latency_seconds"}
            for observation in observations
        ]
        observation_hash = _canonical_sha(semantic_observations)
        observation_hashes.append(observation_hash)
        exact_capability_gate = all(
            isinstance(metric, dict)
            and metric.get("observations") == 100
            and metric.get("layercake_passes") == 100
            and metric.get("source_passing_regressions") == 0
            and metric.get("automatic_route_accuracy") == 1.0
            and metric.get("bounded_zero_regression_pass") is True
            for metric in capability_metrics.values()
        )
        passed = (
            evidence.get("schema_version") == VALIDATION_FORMAT
            and evidence.get("status") == "PASS"
            and evidence.get("split") == "validation"
            and evidence.get("observation_count")
            == gate.get("functional_observations")
            and len(capability_metrics) == gate.get("capabilities")
            and exact_capability_gate
            and evidence.get("bounded_zero_regression_pass") is True
            and evidence.get("complete_locked_depth") is True
            and evidence.get("host_manifest_sha256")
            == candidate.get("host_manifest_sha256")
            and evidence.get("runtime_graph_sha256")
            == candidate.get("runtime_graph_sha256")
            and evidence.get("teacher_present_at_inference") is False
            and evidence.get("source_transformer_blocks_retained") == 0
            and evidence.get("final_test_accessed") is False
        )
        if not passed:
            raise DomainConformanceError(
                f"{initialization.get('id')} failed the reproduction gate"
            )
        rows.append(
            {
                "id": initialization["id"],
                "fresh_process": True,
                "fresh_runtime_session": True,
                "evidence_path": relative,
                "evidence_file_sha256": _sha256_file(path),
                "evidence_claim_sha256": claimed_hash,
                "semantic_observation_payload_sha256": observation_hash,
                "observation_count": evidence["observation_count"],
                "capability_count": len(capability_metrics),
                "layercake_passes": sum(
                    metric["layercake_passes"]
                    for metric in capability_metrics.values()
                ),
                "source_passing_regressions": sum(
                    metric["source_passing_regressions"]
                    for metric in capability_metrics.values()
                ),
                "minimum_automatic_route_accuracy": min(
                    metric["automatic_route_accuracy"]
                    for metric in capability_metrics.values()
                ),
                "peak_process_rss_bytes": evidence["peak_process_rss_bytes"],
                "status": "PASS",
            }
        )

    if len(set(observation_hashes)) != 1:
        raise DomainConformanceError(
            "fresh initializations produced different validation observations"
        )
    aggregate: dict[str, Any] = {
        "format": EVIDENCE_FORMAT,
        "status": "PASS",
        "protocol": {
            "path": str(protocol_path),
            "sha256": _sha256_file(protocol_path),
        },
        "candidate": candidate,
        "reproduction_unit": protocol["reproduction_unit"],
        "initialization_count": len(rows),
        "all_initializations_passed": True,
        "byte_identical_semantic_observation_payloads": True,
        "initializations": rows,
        "teacher_present_at_inference": False,
        "source_transformer_blocks_retained": 0,
        "final_test_accessed": False,
        "claim_boundary": protocol["claim_boundary"],
    }
    aggregate["evidence_sha256"] = _canonical_sha(aggregate)
    _write_json(output_path, aggregate)
    return aggregate


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--protocol", required=True)
    parser.add_argument("--output", required=True)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    evidence = aggregate_host_reproduction(
        protocol_path=args.protocol,
        output_path=args.output,
    )
    print(json.dumps(evidence, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
